@startuml
class InGameView <<MonoBehaviour>> {
}
note bottom: ゲームのUIを管理するクラス
InGameView --> "CharacterDispaly" CharacterDispaly
InGameView --> "SongFrameManager" SongFrameManager
InGameView --> "result" Result
@enduml
