@startuml
!include .\..\..\Interfaces\IInputProvider.puml
class InputProvider {
    + KeyCount() : int
    + ManualUpdate() : void
    + IsPushAllLanes() : List<bool>
    + Initialize() : void
    + SubscriptForKeyDownAction(lane:int, actions:Action[]) : void
    + SubscriptForKeyDownOnceAction(lane:int, actions:Action[]) : void
}
note bottom: 本番用の音ゲー中のキー入力
IInputProvider <|-- InputProvider
InputProvider .> InputKey
@enduml
