@startuml

!include .\\Audio\SoundManager.puml
    !include .\\Classes\CharacterDispaly.puml
    !include .\\Classes\FileLoader.puml
    !include .\\Classes\FPSChecker.puml
    !include .\\Classes\Light.puml

    !include .\\Classes\NotesJudgementDisplay.puml
    !include .\\Classes\NotesLoader.puml
    !include .\\Classes\NotesManager.puml
    !include .\\Classes\Result.puml
    !include .\\Classes\SongFrame.puml
    !include .\\Classes\SongFrameManager.puml
        !include .\\Interfaces\ITriggerEntry.puml
        !include .\\Classes\TriggerEntry.puml
    package Notes {
        !include .\\Abstracts\BaseNote.puml
        !include .\\Classes\LongNote.puml
        !include .\\Classes\Note.puml
    }
    package InputSystem {
        !include .\\Classes\Inputs\DebugInputProvider.puml
        !include .\\Classes\Inputs\DebugSelectInputProvider.puml
        !include .\\Classes\Inputs\InputProvider.puml
        !include .\\Classes\Inputs\SelectInputProvider.puml
        !include .\\Classes\InputKey.puml
        !include .\\Interfaces\IInputProvider.puml
        !include .\\Interfaces\ISelectInputProvider.puml
    }
    folder Model {
    !include .\\Classes\Model\ComboDisplayModel.puml
    !include .\\Classes\Model\InGameModel.puml
    !include .\\Classes\Model\NoteSpeedDisplayModel.puml
    }
    folder Presenter {
    !include .\\Classes\Presenter\ComboDisplayPresenter.puml
    !include .\\Classes\Presenter\InGamePresenter.puml
    !include .\\Classes\Presenter\NoteSpeedDisplayPresenter.puml
    }
    folder View {
        !include .\\Classes\View\ComboDisplayView.puml
        !include .\\Classes\View\InGameView.puml
        !include .\\Classes\View\NoteSpeedDisplayView.puml
    }
        !include .\\Interfaces\IFileLoader.puml
    folder Singleton {
        !include .\\Singleton\Singleton.puml
        !include .\\Singleton\TimeManager.puml
    }



@enduml
