@startuml

    !include .\\Classes\CharacterDispaly.puml
    !include .\\Classes\FileLoader.puml

    !include .\\Classes\NotesLoader.puml
    !include .\\Classes\Result.puml
    !include .\\Classes\SongFrameManager.puml
    folder Model {
    !include .\\Classes\Model\ComboDisplayModel.puml
    !include .\\Classes\Model\InGameModel.puml
    !include .\\Classes\Model\NoteSpeedDisplayModel.puml
    }
    folder Presenter {
    !include .\\Classes\Presenter\ComboDisplayPresenter.puml
    !include .\\Classes\Presenter\InGamePresenter.puml
    !include .\\Classes\Presenter\NoteSpeedDisplayPresenter.puml
    }
    folder View {
        !include .\\Classes\View\ComboDisplayView.puml
        !include .\\Classes\View\InGameView.puml
        !include .\\Classes\View\NoteSpeedDisplayView.puml
    }
        !include .\\Interfaces\IFileLoader.puml




@enduml
