@startuml

        !include .\\Interfaces\ITriggerEntry.puml
        !include .\\Classes\TriggerEntry.puml
    package Notes {
        !include .\\Abstracts\BaseNote.puml
        !include .\\Classes\LongNote.puml
        !include .\\Classes\Note.puml
    }
    package InputSystem {
        !include .\\Classes\Inputs\DebugInputProvider.puml
        !include .\\Classes\Inputs\DebugSelectInputProvider.puml
        !include .\\Classes\Inputs\InputProvider.puml
        !include .\\Classes\Inputs\SelectInputProvider.puml
        !include .\\Classes\InputKey.puml
        !include .\\Interfaces\IInputProvider.puml
        !include .\\Interfaces\ISelectInputProvider.puml
    }



@enduml
